Backend-RoR/excoincial-barong/config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  mount Lines::Engine => "/blog"
  use_doorkeeper


  devise_for :accounts, controllers: {sessions: :sessions,
                                      confirmations: :confirmations,
                                      registrations: :registrations,
                                      unlocks: :unlocks,
                                      passwords: :passwords},
                        path: "/accounts",
                        path_names: {sign_in: 'login',
                                     password: 'forgot',
                                     confirmation: 'confirm',
                                     unlock: 'unlock',
                                     sign_up: 'register',
                                     sign_out: 'logout'
                                     }
  devise_scope :account do
    match '/accounts/login/confirm', to: 'sessions#confirm', via: %i[get post], as: 'account/login', action: 'confirm'
    match '/accounts/register/confirm', to: 'registrations#confirm', via: %i[get post], as: 'account/register', action: 'confirm'
    match '/accounts/logout', to: 'sessions#destroy', via: %i[get], as: 'account/logout', action: 'destroy'
#    match '/accounts/forgot', to: 'passwords#update', via: %i[put patch], as: 'account/forgot'
#    match '/accounts/forgot', to: 'passwords#create', via: %i[post], as: 'account/forgot'
#    match '/accounts/forgot/new', to: 'passwords#new', via: %i[get post], as: 'account/forgot', action: 'new'
#    match '/accounts/forgot/edit', to: 'passwords#edit', via: %i[get post], as: 'account/forgot', action: 'edit'
#    match '/register/create', to: 'registrations#create', via: %i[get post]
#    match '/register', to: 'registrations#new', via: %i[get post]
    match '/accounts/unlock', to: 'unlocks#show', via: %i[get post]

    match '/accounts/sign_in', to: 'sessions#new', via: %i[get], as: 'new_account_sign_in', action: 'new'
    match '/accounts/sign_in', to: 'sessions#create', via: %i[post], as: 'account/sign_in', action: 'create'
    match '/accounts/sign_in/confirm', to: 'sessions#confirm', via: %i[get post], as: 'confirm_account_sign_in', action: 'confirm'
    match '/accounts/sign_up', to: 'registrations#new', via: %i[get post], as: 'new_account_sign_up', action: 'new'
    match '/accounts/sign_up/confirm', to: 'registrations#confirm', via: %i[get post], as: 'account/sign_up', action: 'confirm'
    match '/accounts/sign_out', to: 'sessions#destroy', via: %i[get], as: 'account/sign_out', action: 'destroy'
    match '/accounts/password', to: 'passwords#update', via: %i[put patch], as: 'update_accounts_password'
    match '/accounts/password', to: 'passwords#create', via: %i[post], as: 'create_accounts_password'
    match '/accounts/password/new', to: 'passwords#new', via: %i[get post], as: 'new_accounts_password', action: 'new'
    match '/accounts/password/edit', to: 'passwords#edit', via: %i[get post], as: 'edit_accounts_password', action: 'edit'
    match '/accounts/confirmation/new', to: 'sessions#new', via: %i[get post], as: 'new_accounts_confirmation', action: 'new'
    match '/accounts/confirmation', to: 'sessions#create', via: %i[post], as: 'create_accounts_confirmation'
    match '/accounts/confirmation', to: 'sessions#show', via: %i[get], as: 'accounts/confirmation'
  end

#  post '/register', to: 'registrations#new', as: :registation
  # root to: 'index#index', as: :index

  scope :users do
    mount UserApi::Base, at: '/api'
    mount ManagementAPI::V1::Base, at: '/management_api'

    get '/', to: 'index#index', as: :index
    post 'phones/verification', to: 'phones#verify'

    get 'security', to: 'security#enable'
    post 'security/confirm', to: 'security#confirm'

    get 'health/alive', to: 'health#alive'
    get 'health/ready', to: 'health#ready'
    get 'welcome/disable_account', to: redirect('member/:id/disable_account')

    resources :phones, only: %i[new create]
    resources :profiles, only: %i[new create]
    resources :documents, only: %i[new create]

    namespace :admin do
      get '/', to: 'accounts#index', as: :accounts
      resources :accounts, except: %i[new create] do
        post :disable_2fa, on: :member

        resources :labels, except: %i[index show]
      end
      resources :websites
      resources :profiles, only: %i[edit update] do
        put :document_label, on: :member
      end
    end
  end

end

Backend-RoR/excoincial-barong/app/models/website.rb
# frozen_string_literal: true

#
# Website
#
class Website < ApplicationRecord
end

# == Schema Information
# Schema version: 20190626065821
#
# Table name: websites
#
#  id           :bigint(8)        not null, primary key
#  domain       :string(255)
#  title        :string(255)
#  logo         :string(255)
#  favicon      :string(255)
#  stylesheet   :string(255)
#  header       :text(65535)
#  footer       :text(65535)
#  redirect_url :string(255)
#  state        :string(255)
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#
# Indexes
#
#  index_websites_on_domain  (domain) UNIQUE
#

Backend-RoR/excoincial-barong/app/controllers/admin/websites_controller.rb
# frozen_string_literal: true

module Admin
  class WebsitesController < ModuleController
    before_action :set_website, only: %i[show edit update destroy]

    def index
      @websites = Website.all
    end

    def show
    end

    def new
      @website = Website.new
    end

    def edit
    end

    def create
      @website = Website.new(website_params)

      if @website.save
        redirect_to admin_websites_url, notice: 'Website was successfully created.'
      else
        render :new
      end
    end

    def update
      if @website.update(website_params)
        redirect_to admin_websites_url, notice: 'Website was successfully updated.'
      else
        render :edit
      end
    end

    def destroy
      @website.destroy
      redirect_to admin_websites_url, notice: 'Website was successfully destroyed.'
    end

  private

    def set_website
      @website = Website.find(params[:id])
    end

    def website_params
      params.require(:website)
            .permit(:domain, :title, :logo, :stylesheet, :favicon,
                    :header, :footer, :redirect_url, :state)
    end
  end
end

Backend-RoR/excoincial-barong/app/views/admin/websites/_form.html.erb
<%= form_with(model: [:admin, @website], local: true) do |form| %>
  <% if website.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(website.errors.count, "error") %> prohibited this website from being saved:</h2>

      <ul>
        <% website.errors.full_messages.each do |message| %>
            <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <%= form.label :domain, class: 'control-label'%>
  <%= form.text_field :domain, id: :website_domain , class: 'form-control col-sm-10'%>
  <br>

  <%= form.label :title, class: 'control-label'%>
  <%= form.text_field :title, id: :website_title , class: 'form-control col-sm-10'%>
  <br>

  <%= form.label :logo, class: 'control-label'%>
  <%= form.text_field :logo, id: :website_logo , class: 'form-control col-sm-10'%>
  <br>

  <%= form.label :favicon, class: 'control-label'%>
  <%= form.text_field :favicon, id: :website_favicon , class: 'form-control col-sm-10'%>
  <br>

  <%= form.label :stylesheet, class: 'control-label'%>
  <%= form.text_field :stylesheet, id: :website_stylesheet , class: 'form-control col-sm-10'%>
  <br>

  <%= form.label :header, class: 'control-label'%>
  <%= form.text_area :header, id: :website_header , class: 'form-control col-sm-10'%>
  <br>

  <%= form.label :footer, class: 'control-label'%>
  <%= form.text_area :footer, id: :website_footer , class: 'form-control col-sm-10'%>
  <br>

  <%= form.label :redirect_url, class: 'control-label'%>
  <%= form.text_field :redirect_url, id: :website_redirect_url , class: 'form-control col-sm-10'%>
  <br>

  <%= form.label :state, class: 'control-label'%>
  <%= form.text_field :state, id: :website_state , class: 'form-control col-sm-10'%>
  <br>

  <%= form.submit 'Submit', class: 'btn btn-primary' %>
  <%= link_to t('doorkeeper.applications.buttons.cancel'), admin_websites_path,  class: 'btn btn-default' %>
  <br>
  <br>

<% end %>

Backend-RoR/excoincial-barong/app/views/admin/websites/edit.html.erb
<div class="container">
  <h1>Editing Website</h1>
  <%= render 'form', website: @website %>
  <br>
</div>

Backend-RoR/excoincial-barong/app/views/admin/websites/index.html.erb
<div class="container">

  <h1>Websites</h1>
  <%= link_to 'New Website', new_admin_website_path, class: 'btn btn-success' %>
  <br><br>

  <table class="table table-bordered table-striped table-hover table-sm text-center">
    <thead>
      <tr>
        <th>ID</th>
        <th>Domain</th>
        <th>Title</th>
        <th>Logo</th>
        <th>Stylesheet</th>
        <th>Header</th>
        <th>Footer</th>
        <th>Redirect url</th>
        <th>State</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @websites.each do |website| %>
        <tr>
          <td><%= website.id %></td>
          <td><%= website.domain %></td>
          <td><%= website.title %></td>
          <td><%= website.logo %></td>
          <td><%= website.stylesheet %></td>
          <td><%= website.header %></td>
          <td><%= website.footer %></td>
          <td><%= website.redirect_url %></td>
          <td><%= website.state %></td>
          <td><%= link_to 'Show', admin_website_path(website), class: 'btn btn-info btn-sm' %></td>
          <td><%= link_to 'Edit', edit_admin_website_path(website), class: 'btn btn-primary btn-sm' %></td>
          <td><%= link_to 'Delete', admin_website_path(website), class: 'btn btn-danger btn-sm', method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

Backend-RoR/excoincial-barong/app/views/admin/websites/new.html.erb
<div class="container">
  <h1>New Website</h1>

  <%= render 'form', website: @website %>

</div>

Backend-RoR/excoincial-barong/app/views/admin/websites/show.html.erb
<div class="container">
  <p id="notice"><%= notice %></p>
  <h1>Website</h1>
  <ul class="list-group">
    <li class="list-group-item">
      <b> Domain: </b>
      <%= @website.domain%>
    </li>

    <li class="list-group-item">
      <b> Title: </b>
      <%= @website.title%>
    </li>

    <li class="list-group-item">
      <b> Logo: </b>
      <%= @website.logo%>
    </li>

    <li class="list-group-item">
      <b> Stylesheet: </b>
      <%= @website.stylesheet%>
    </li>

    <li class="list-group-item">
      <b> Header: </b>
      <%= @website.header%>
    </li>

    <li class="list-group-item">
      <b> Footer: </b>
      <%= @website.footer%>
    </li>

    <li class="list-group-item">
      <b> Redirect Url: </b>
      <%= @website.redirect_url%>
    </li>

    <li class="list-group-item">
      <b> State: </b>
      <%= @website.state%>
    </li>
  </ul>
  <br>
  <%= link_to 'Edit', edit_admin_website_path(@website), class: 'btn btn-primary' %>
  <%= link_to 'Cancel', admin_websites_path, class: 'btn btn-default' %>
</div>